name: run tests

on:
  workflow_dispatch:
  push:

env:
  CS_NUGET_TEMPLATE_DOTNET_VERSION: 8


jobs:
  test-debug:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: $CS_NUGET_TEMPLATE_DOTNET_VERSION

      - run: dotnet test src -c Release
      - run: dotnet test src-c Debug