name: test-every-push-to-every-branch

on:
  workflow_call:
  workflow_dispatch:
  push:

env:
  CS_NUGET_TEMPLATE_DOTNET_VERSION: 8

jobs:

  test-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.CS_NUGET_TEMPLATE_DOTNET_VERSION }}
      - run: dotnet test src -c Debug

  test-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.CS_NUGET_TEMPLATE_DOTNET_VERSION }}
      - run: dotnet test src -c Release
