name: find-version

on:
  workflow_call:
  workflow_dispatch:

jobs:
  find-version:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: gittools/actions/gitversion/setup@v3.1.11
        with:
          versionSpec: '6.0.x'

      - uses: gittools/actions/gitversion/execute@v3.1.11
        id: version_step
